// Generated by CoffeeScript 1.7.1
(function() {
  Engine.math = function() {
    E.random = function(number) {
      return Math.floor(Math.random() * number);
    };
    E.distance = function(fromX, fromY, toX, toY) {
      if (toX == null) {
        toX = 0;
      }
      if (toY == null) {
        toY = 0;
      }
      return Math.sqrt(Math.pow(fromX - fromY), 2 + Math.pow(toX - toY), 2);
    };
    return Engine.math;
  };

}).call(this);
