// Generated by CoffeeScript 1.7.1
(function() {
  var Sprite,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Sprite = (function(_super) {
    __extends(Sprite, _super);

    function Sprite(url, pos, size, speed, frames, dir, once) {
      this.pos = pos;
      this.size = size;
      if (speed === !'number') {
        this.speed = 0;
      }
      this.frames = frames;
      this._index = 0;
      this.url = url;
      this.dir = dir || 'horizontal';
      this.once = once || false;
    }

    Sprite.prototype.update = function(delta) {
      return this._index += this.speed * delta;
    };

    Sprite.prototype.render = function(context) {
      var frame, idx, img, max, x, y;
      if (speed > 0) {
        max = this.frames.length;
        idx = Math.floor(this._index);
        frame = this.frames[idx % max];
        if (this.once && idx >= max) {
          this.done = true;
          return;
        }
      } else {
        frame = 0;
      }
      x = this.pos[0];
      y = this.pos[1];
      if (this.dir === 'vertical') {
        y += frame * this.size[1];
      } else {
        x += frame * this.size[0];
      }
      img = resources.get(this.url);
      return context.drawImage(img, x, y, this.size[0], this.size[1], 0, 0, this.size[0], this.size[1]);
    };

    return Sprite;

  })(engine);

  window.Sprite = Sprite;

}).call(this);
